name: Build
on:
  push:
  pull_request:
permissions:
  contents: write
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: mskelton/setup-pnpm@v1
      - name: ESLint
        run: pnpm lint
      - name: Prettier
        run: pnpm prettier --check .
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: mskelton/setup-pnpm@v1
      - name: Type check
        run: pnpm ts
  release:
    needs: [lint, typecheck]
    runs-on: ubuntu-latest
    steps:
      - uses: mskelton/setup-pnpm@v1
      - name: Build
        run: pnpm build
      - name: Build types
        run: pnpm ts
      - name: Release
        run: pnpm semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
